import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "../components/navigation";
import icon from "../image/icon.png";
import { UserProvider } from "./context/UserContext";

import { Prompt } from "next/font/google";
import "./globals.css";

const prompt = Prompt({
  subsets: ["thai", "latin"],
  weight: ["300"],
  variable: "--font-prompt",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"], 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MY Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="icon" href={icon.src} />
      </head>
      <body className="min-h-full flex flex-col">
        <UserProvider>
          <Navber />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
